# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
  #reids配置
  cache:
    redis:
      redis:
      host: 127.0.0.1
      port: 6379
      password:
      time-to-live: 90000
#配置Mybatis-plus的相关属性
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8001
