server:
  port: 8002
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  servlet:
    multipart:
      max-file-size: 200MB       #总上传的最大值
      max-request-size: 100MB    #单个文件的最大值

