spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-basic?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
#配置Mybatis的相关属性
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mapper XML文件的位置
  type-aliases-package: com.javaee.mybatisbasic.entity  #指定实体类的别名的映射路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印输出SQL语句
    map-underscore-to-camel-case: true   # 启动驼峰式转换
    use-generated-keys: true      #开启自增主键
server:
  port: 8001
